<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PlantMachineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    use WithoutModelEvents;

    public function run(): void
    {
        $plantMachineData = [
            'Plant A' => [
                'HD-10C',
                'TW-RBD-CU',
                'MD-1',
                'MULTI DRAWING-1',
                'MULTI DRAWING-2',
                'BC-Samp5',
                'BC-Samp6',
                'BC-Samp7',
                'BC-5',
                'BC-6',
                'EX-70+40',
                'EX-60A',
                'EX-60B',
                'EX-80+60',
                'EX-80H',
                'EX-80G',
                'CB-4C',
                'CB-7E',
                'TW-125C',
                'ST-7F',
                'EX-70A',
                'CB-16B',
                'CB-48A',
                'ST-30A',
                'ST-66',
                'REW-30A',
                'REW-67',
                'REW-8A',
                'EX-90+80',
                'EX-90F',
                'EX-90D',
                'EX-90K',
                'EX-120D',
                'EX-120+70',
                'CB-1F',
                'CL-1',
                'CL-2',
                'CL-3',
                'CL-4',
                'CL-5',
                'CL-6',
                'CL-7',
                'CL-8',
                'MC-1',
                'MC-2',
                'MC-3',
                'REW-AR-21',
                'AR-21',
                'REW-AR-72B-1',
                'REW-AR-72B-2',
                'AR-72B'
            ],
            'Plant A - Autowire' => [
                'MULTI DRAWING-3',
                'BC-Samp1',
                'BC-Samp2',
                'BC-Samp3',
                'BC-Samp4',
                'BC-Samp9',
                'BC-Samp10',
                'AW-1',
                'AW-2',
            ],
            'Plant B' => [
                'RBD-AL',
                'HD-10A',
                'HD-8C',
                'HD-8E',
                'MD-5',
                'MD-6',
                'MD-7',
                'OVEN',
                'ST-7H',
                'ST-7I',
                'ST-6B',
                'ST-7D',
                'ST-7A',
                'ST-7J',
                'ST-12B',
                'ST-19C',
                'ST-30B',
                'ST-54A',
                'ST-54C',
                'ST-54E',
                'EX-90B',
                'EX-100B',
                'CB-2B',
                'CB-2C',
                'CB-4B',
                'REW-1',
                'REW-2',
                'REW-3',
                'REW-4',
                'ST-54B',
                'ST-54D',
                'AR-72',
                'WR-1'
            ],
            'Plant C' => [
                'MD-2C',
                'MD-3C',
                'TW-MD',
                'FD-9',
                'FD-10',
                'FD-11',
                'FD-12',
                'FD-20',
                'FD-21',
                'TIN-1',
                'TIN-2',
                'TIN-3',
                'ELECTRO PLATING',
                'BC-1C',
                'BC-2C',
                'BC-3C',
                'BC-4C',
                'BC-5C',
                'BC-7',
                'BC-8',
                'BC-9',
                'BC-10',
                'TV-5',
                'TV-6',
                'TV-7',
                'TV-8',
                'TV-9',
                'TV-10',
                'TV-11',
                'TV-12',
                'EX-65 1C',
                'EX-65 2C',
                'EX-80+50 A',
                'EX-80+50 B',
                'EX-65 3C',
                'EX-65 4C',
                'TW-630 A',
                'TW-630 B',
                'TW-800A',
                'TW-800B',
                'TW-125A',
                'TW-125B',
                'CB-16A',
                'CB-16C',
                'CB-20A',
                'EX-80J',
                'EX-90E',
                'EX-120F',
                'EX-150C',
                'EX-120A',
                'EX-120/100D',
                'ST-12A',
                'REW-TWB-16',
                'TWB-16A',
                'TWB-16B',
                'REW-TWB-24A',
                'REW-TWB-24B',
                'TWB-24A',
                'TWB-24B',
                'TWB-24C',
                'TWB-24D',
                'TWB-24E',
                'REW-SWB-24A',
                'REW-SWB-24B',
                'SWB-24A',
                'SWB-24B',
                'SWB-24C',
                'SWB-24D',
                'SWB-24E',
                'REW-SWB-32A',
                'REW-SWB-32B',
                'SWB-32A',
                'SWB-32B',
                'REW-SWB-48A',
                'SWB-48',
                'TP-10'
            ],
            'Plant D' => [
                'REW-5',
                'REW-6',
                'REW-7',
                'TP-5',
                'TP-6',
                'TP-8',
                'TP-2',
                'TP-11',
                'TP-1',
                'TP-3',
                'TP-4',
                'EX--100A',
                'CB-26A',
                'CB-26B',
                'EX--100C',
                'EX--120B',
                'EX--120C',
                'EX--160A',
                'TP-7'
            ],
            'Plant D - CCV' => [
                'CCV-JHON ROYLE',
                'CCV-PAMPASS',
                'CCV-SUMITOMO'
            ],
            'Plant E' => [
                'COL-4A',
                'COL-4B',
                'COL-9F',
                'COL-5F',
                'COL-8F A',
                'COL-8F B',
                'EX-45-7F',
                'EX-45-8F',
                'EX-45-9F',
                'EX-45-10F',
                'EX-45-11F',
                'EX-45-12F',
                'EX-45-13F',
                'EX-45-14F',
                'EX-45-15F',
                'EX-45-16F',
                'EX-45-17F',
                'EX-30F',
                'EX-50F',
                'PATH CORD',
                'PIG TAILD',
                'DC-1',
                'DC-2',
                'DC-3',
                'CB-4F',
                'CB-5F',
                'CB-6F',
                'CB-7F',
                'CB-8F',
                'CB-9F',
                'EX-90G',
                'EX-90H',
                'EX-90I',
                'EX-90J'
            ],
            'FA' => [],
            'FH' => [],
            'FO' => [],
            'GA - TANGERANG' => [],
            'GA - JAKARTA' => [],
            'Gudang Jadi' => [],
            'HC' => [],
            'IT' => [],
            'JEMBO ENERGINDO' => [],
            'Konstruksi' => [],
            'Marketing' => [],
            'MT' => [],
            'PE' => [],
            'Plant Tools' => [],
            'PP' => [],
            'PROCUREMENT' => [],
            'QC FO' => [],
            'QC Lab' => [],
            'QC LV' => [],
            'QC MV' => [],
            'QR' => [],
            'Sales' => [],
            'SS' => [],
            'RM Office' => [],
            'RM 1' => [],
            'RM 2' => [],
            'RM 3' => [],
            'RM 5' => [],
        ];

        foreach ($plantMachineData as $plantName => $machinesList) {
            $plantId = DB::table('plants')->insertGetId([
                'name' => $plantName,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);

            if (!empty($machinesList)) {
                $machineBatch = [];
                foreach ($machinesList as $machineName) {
                    $machineBatch[] = [
                        'plant_id' => $plantId,
                        'name' => $machineName,
                        'created_at' => Carbon::now(),
                        'updated_at' => Carbon::now()
                    ];
                }
                DB::table('machines')->insert($machineBatch);
            }
        }
    }
}
